- name: Deploy the war fromS3 Bucket file
  hosts: all
  become: yes
  vars:
    TOMCAT_LOC: /home/student/apache-tomcat-8.5.78
    LOCAL_WAR: /var/lib/jenkins/workspace/CI-CD-Job/target

  tasks: 
     - name: Check the directory exists or not 
       shell: ls -ld {{TOMCAT_LOC}}

     - name: Find the war files in the directory
       find:
        paths: "{{TOMCAT_LOC}}/webapps/"
       register: out 

     - debug: 
          msg: "{{out}}"  

     - name: Remove file (delete file)
       file:
          path: "{{TOMCAT_LOC}}/webapps/student.war"
          state: absent 
       ignore_error: yes

     - name: Find the war files in the directory
       find:
        paths: "{{TOMCAT_LOC}}/webapps/"
       register: out 

     - debug: 
          msg: "{{out}}"           
        
    #  - name: Find the local war file 
    #    command: ls "{{LOCAL_WAR}}/studentapp-0.1.0.6-SNAPSHOT.war"
    #    delegate_to: 127.0.0.1 
    #    become: no 
    #    register: out

    #  - debug:
    #      msg: "{{out}}" 

     - name: Install Python2 Pip Module 
       yum:
          name: python2-pip
          state: installed 

     - name: Install the botocore2 and boto   
       pip:
          name: "{{item}}"
       loop: 
          - botocore
          - boto3   
          - boto     
        
    #  - name: Downloading war file from s3_bucket
    #    aws_s3:
    #       bucket: clouddevops-42-test
    #       object: student-{{ MAJOR }}.{{ MINOR }}.{{ BUILDNUMBER }}.war
    #       dest: "{{TOMCAT_LOC}}/webapps/student.war"
    #       mode: get
    #    become_user: student

     - name: Download the Artifact from S3 Bucket
       aws_s3:
        bucket: terrafrom-learning-bucket
        object: "student.war-{{ MAJOR }}.{{ MINOR }}.{{ BUILDN }}.war" 
        dest: "{{ TOMCAT_LOC }}/webapps/student.war"
        mode: get      
       become_user: student  

     - name: 
       shell: sudo systemctl restart student




#clouddevops-42-test
    #  - name: Download the Artifact from S3 Bucket
    #    get_url:
    #     url: "https://cloud-devops-batch41.s3.us-east-2.amazonaws.com/student-{{ MAJOR }}.{{ MINOR }}.{{ BUILDNUMBER }}.war"
    #     dest: "{{TOMCAT_LOC}}/webapps/student.war"
    #     mode: '0775'      

# ### This is not the suggested way //// Verma needs to figure out the production grade ###
#      - name: Download foo.conf
#        get_url:
#             url: https://cloud-devops-batch41.s3.us-east-2.amazonaws.com/student-0.1.31.war
#             dest: "{{TOMCAT_LOC}}/webapps/student.war"
#             mode: '0550'
#        become_user: student
  
    # - name: Download foo.conf
    #   get_url:
    #     url: http://example.com/path/file.conf
    #     dest: /etc/foo.conf
    #     mode: '0440'







































