- name: Deploy the war file
  hosts: all
  become: yes
  vars:
    TOMCAT_LOC: /home/student/apache-tomcat-8.5.78
    LOCAL_WAR: /var/lib/jenkins/workspace/CICD/target
              
#  /studentapp-studentapp.war

  tasks: 
     - name: Check the directory exists or not 
       shell: ls -ld {{TOMCAT_LOC}}

     - name: Find the war files in the directory
       find:
        paths: "{{TOMCAT_LOC}}/webapps/"
       register: out 

     - debug: 
          msg: "{{out}}"  

     - name: Remove file (delete file)
       file:
          path: "{{TOMCAT_LOC}}/webapps/student.war"
          state: absent 
       ignore_errors: yes 

     - name: Find the war files in the directory
       find:
        paths: "{{TOMCAT_LOC}}/webapps/"
       register: out 

     - debug: 
          msg: "{{out}}"           
        
    #  - name: Find the local war file 
    #    command: ls "{{LOCAL_WAR}}/studentapp-0.1.0.6-SNAPSHOT.war"
    #    delegate_to: 127.0.0.1 
    #    become: no 
    #    register: out

    #  - debug:
    #      msg: "{{out}}" 

     - name: Copy the war file
       copy: 
         src: "{{LOCAL_WAR}}/studentapp-studentapp.war"
         dest: "{{TOMCAT_LOC}}/webapps/student.war" 
         mode: '0775'



     - name: Start httpd service 
       service:
          name: student
          state: restarted











































