- name: Do Production Deployment
  hosts: all
  become: yes
  tasks: 
     - name: Remove the Old War File 
       file:  
          path: "{{item}}"
          state: absent 
       loop: 
           - /home/student/apache-tomcat-8.5.56/webapps/student
           - /home/student/apache-tomcat-8.5.56/webapps/student.war
     
     - name: Download the artifact from Nexus 
       get_url: 
          url: "http://13.235.45.200:8081/repository/student-project-release/com/jdevs/studentapp/{{VERSION}}-RELEASE/studentapp-{{VERSION}}-RELEASE.war"
          dest: "/home/student/apache-tomcat-8.5.56/webapps/student.war"
       become_user: student  